spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kisscam
    username: postgres
    password: postgres

#Application config
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000