spring:
  profiles:
    active:
    -  local
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        lob:
          non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
      
      
logging:
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss:SSS XXX}] [%-5level] [%thread] [%X{trace-id}] %logger{36} : %msg%n'
  file:
    name: '/apps/icms.log'

#Application config
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 18000000